org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.jvmargs=-Dfile.encoding=UTF-8 -Xmx4g
org.gradle.kotlin.dsl.allWarningsAsErrors=true
org.gradle.parallel=true


# https://kotlinlang.org/docs/whatsnew2220.html#preview-improved-incremental-compilation-for-kotlin-jvm
# TODO: https://issuetracker.google.com/issues/558362037
#kotlin.incremental.jvm.fir=true
