// Stabilize all classes in core data package.
com.github.kr328.clash.model.*

// Consider kotlin collections stable.
kotlin.collections.*

// Consider kotlinx.datetime models stable.
kotlinx.datetime.DayOfWeek
kotlin.time.Instant
kotlinx.datetime.LocalDate
kotlinx.datetime.LocalDateTime
kotlinx.datetime.LocalTime
kotlinx.datetime.TimeZone
kotlin.time.Duration

// Consider Date/UUID/stuff stable.
java.util.*

kotlinx.coroutines.CoroutineScope
