name: Build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - trunk

jobs:
  check-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 25
      - uses: gradle/actions/setup-gradle@v6
      - run: ./gradlew spotlessCheck --no-daemon

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: actions/setup-go@v6
        with:
          go-version: "1.26"
          check-latest: true
          cache: true
          cache-dependency-path: |
            core/src/main/golang/go.sum
            core/src/foss/golang/go.sum
            core/src/foss/golang/clash/go.sum
      - uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 25
      - uses: gradle/actions/setup-gradle@v6
      - run: ./gradlew lintDebug --no-daemon

  build:
    permissions:
      id-token: write
      attestations: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: actions/setup-go@v6
        with:
          go-version: "1.26"
          check-latest: true
          cache: true
          cache-dependency-path: |
            core/src/main/golang/go.sum
            core/src/foss/golang/go.sum
            core/src/foss/golang/clash/go.sum
      - uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 25
      - uses: gradle/actions/setup-gradle@v6
      - run: ./gradlew app:assembleRelease --no-daemon
      - name: Generate Artifact Attestation
        uses: actions/attest@v4
        with:
          subject-path: app/build/outputs/apk/release/*.apk
      - name: Delete release if exist then create release
        if: github.repository_owner == 'Goooler' && github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete nightly --cleanup-tag -y || true
          gh release create nightly "./app/build/outputs/apk/release/"*.apk --prerelease --generate-notes

  # Status check that is required in branch protection rules.
  final-status:
    needs:
      - check-style
      - lint
      - build
    runs-on: ubuntu-slim
    if: always()
    steps:
      - name: Check
        run: |
          results=$(tr -d '\n' <<< '${{ toJSON(needs.*.result) }}')
          if ! grep -q -v -E '(failure|cancelled)' <<< "$results"; then
            echo "One or more required jobs failed"
            exit 1
          fi
          echo "All required jobs completed successfully."
