name: Build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - trunk

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: 21
      - uses: gradle/actions/setup-gradle@v6
      - name: Build
        run: |
          ./gradlew app:assembleMetaRelease
      - name: Delete release if exist then create release
        if: github.repository == 'Goooler/ClashMetaForAndroid' && github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release view nightly && gh release delete nightly -y --cleanup-tag
          gh release create nightly "./app/build/outputs/apk/meta/release/"*.apk --prerelease --generate-notes
